export type DestinationInfo = {
  slug: string;
  name: string;
  country: string;
  description: string;
  heroImage: string;
  highlights: string[];
  bestTimeToVisit: string;
  averageDays: string;
  language: string;
  currency: string;
  attractions: DestinationAttraction[];
};

export type DestinationAttraction = {
  id: string;
  name: string;
  category: string;
  description: string;
  imageUrl: string;
  priceLevel: number;
  rating: number;
  tags: string[];
};

export const DESTINATIONS_DATA: Record<string, DestinationInfo> = {
  paris: {
    slug: "paris",
    name: "Paris",
    country: "Franca",
    description:
      "A Cidade Luz encanta com sua arquitetura iconica, gastronomia refinada e museus de classe mundial. De passeios romanticos pelo Sena a noites culturais em Montmartre, Paris oferece experiencias inesqueciveis para toda a familia.",
    heroImage: "/images/hero/paris.jpg",
    highlights: ["Gastronomia", "Arte & Museus", "Arquitetura", "Romantica"],
    bestTimeToVisit: "Abril a Junho e Setembro a Outubro",
    averageDays: "4 a 6 dias",
    language: "Frances",
    currency: "Euro (EUR)",
    attractions: [
      {
        id: "par-1",
        name: "Torre Eiffel",
        category: "Monumento",
        description: "Simbolo maximo de Paris com vistas panoramicas de 360 graus da cidade.",
        imageUrl: "/images/demo/paris/par-001.jpg",
        priceLevel: 2,
        rating: 4.6,
        tags: ["icone", "miradouro", "romantico"],
      },
      {
        id: "par-2",
        name: "Museu do Louvre",
        category: "Museu",
        description: "Maior museu de arte do mundo, lar da Mona Lisa e 35.000 obras-primas.",
        imageUrl: "/images/demo/paris/par-002.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["arte", "historia", "cultura"],
      },
      {
        id: "par-3",
        name: "Sacre-Coeur e Montmartre",
        category: "Igreja",
        description: "Basilica branca no ponto mais alto de Paris, com bairro artistico charmoso.",
        imageUrl: "/images/demo/paris/par-003.jpg",
        priceLevel: 0,
        rating: 4.6,
        tags: ["igreja", "arte", "miradouro"],
      },
      {
        id: "par-4",
        name: "Arco do Triunfo",
        category: "Monumento",
        description: "Monumento neoclassico com vista para os Champs-Elysees.",
        imageUrl: "/images/demo/paris/par-004.jpg",
        priceLevel: 2,
        rating: 4.6,
        tags: ["historia", "miradouro"],
      },
      {
        id: "par-5",
        name: "Catedral Notre-Dame",
        category: "Igreja",
        description: "Obra-prima gotica do seculo XII, reaberta apos restauracao.",
        imageUrl: "/images/demo/paris/par-005.jpg",
        priceLevel: 0,
        rating: 4.7,
        tags: ["patrimonio", "gotico", "arquitetura"],
      },
      {
        id: "par-6",
        name: "Museu d'Orsay",
        category: "Museu",
        description: "Museu impressionista numa antiga estacao com Monet, Renoir e Van Gogh.",
        imageUrl: "/images/demo/paris/par-006.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["arte", "impressionismo"],
      },
      {
        id: "par-7",
        name: "Palacio de Versalhes",
        category: "Palacio",
        description: "Residencia real com Salao dos Espelhos e jardins monumentais.",
        imageUrl: "/images/demo/paris/par-007.jpg",
        priceLevel: 3,
        rating: 4.5,
        tags: ["palacio", "jardins", "patrimonio"],
      },
      {
        id: "par-8",
        name: "Jardim de Luxemburgo",
        category: "Parque",
        description: "Jardim elegante com fontes, estatuas e areas para piquenique.",
        imageUrl: "/images/demo/paris/par-008.jpg",
        priceLevel: 0,
        rating: 4.5,
        tags: ["parque", "gratuito", "familia"],
      },
    ],
  },
  roma: {
    slug: "roma",
    name: "Roma",
    country: "Italia",
    description:
      "A Cidade Eterna combina ruinas milenares com a vida moderna italiana. Cada esquina revela um tesouro historico, da grandiosidade do Coliseu a beleza do Vaticano, tudo regado a pizza e gelato.",
    heroImage: "/images/hero/roma.jpg",
    highlights: ["Historia", "Gastronomia", "Arte", "Ruinas Antigas"],
    bestTimeToVisit: "Abril a Junho e Setembro a Novembro",
    averageDays: "4 a 5 dias",
    language: "Italiano",
    currency: "Euro (EUR)",
    attractions: [
      {
        id: "rom-1",
        name: "Coliseu",
        category: "Monumento",
        description: "Anfiteatro romano do seculo I com capacidade para 50.000 espectadores.",
        imageUrl: "/images/demo/roma/rom-001.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["historia", "icone", "patrimonio"],
      },
      {
        id: "rom-2",
        name: "Museus Vaticanos e Capela Sistina",
        category: "Museu",
        description: "Colecao de arte papal com o teto pintado por Michelangelo.",
        imageUrl: "/images/demo/roma/rom-002.jpg",
        priceLevel: 3,
        rating: 4.7,
        tags: ["arte", "religiao", "patrimonio"],
      },
      {
        id: "rom-3",
        name: "Fontana di Trevi",
        category: "Monumento",
        description: "A mais famosa fonte de Roma - jogue uma moeda e garanta sua volta.",
        imageUrl: "/images/demo/roma/rom-003.jpg",
        priceLevel: 0,
        rating: 4.6,
        tags: ["icone", "romantico", "gratuito"],
      },
      {
        id: "rom-4",
        name: "Pantheon",
        category: "Monumento",
        description: "Templo romano de 2.000 anos com a maior cupula de concreto nao armado do mundo.",
        imageUrl: "/images/demo/roma/rom-004.jpg",
        priceLevel: 0,
        rating: 4.8,
        tags: ["historia", "arquitetura", "gratuito"],
      },
      {
        id: "rom-5",
        name: "Forum Romano",
        category: "Monumento",
        description: "Centro da vida publica na Roma antiga com ruinas de templos e basilicas.",
        imageUrl: "/images/demo/roma/rom-005.jpg",
        priceLevel: 2,
        rating: 4.5,
        tags: ["historia", "ruinas"],
      },
      {
        id: "rom-6",
        name: "Basilica de Sao Pedro",
        category: "Igreja",
        description: "Maior igreja do mundo com obras de Michelangelo e Bernini.",
        imageUrl: "/images/demo/roma/rom-006.jpg",
        priceLevel: 0,
        rating: 4.8,
        tags: ["religiao", "arte", "arquitetura"],
      },
      {
        id: "rom-7",
        name: "Trastevere",
        category: "Bairro",
        description: "Bairro boemo com trattorias autenticas, ruas de paralelepipedo e vida noturna.",
        imageUrl: "/images/demo/roma/rom-007.jpg",
        priceLevel: 1,
        rating: 4.5,
        tags: ["gastronomia", "bairro", "cultura"],
      },
      {
        id: "rom-8",
        name: "Piazza Navona",
        category: "Praca",
        description: "Praca barroca com fontes de Bernini, artistas de rua e cafes ao ar livre.",
        imageUrl: "/images/demo/roma/rom-008.jpg",
        priceLevel: 0,
        rating: 4.5,
        tags: ["praca", "arte", "gratuito"],
      },
    ],
  },
  lisboa: {
    slug: "lisboa",
    name: "Lisboa",
    country: "Portugal",
    description:
      "Capital portuguesa de charme singular, com miradouros deslumbrantes, eletricos historicos, pasteis de nata e uma atmosfera acolhedora. A cidade perfeita para quem fala portugues e quer se sentir em casa na Europa.",
    heroImage: "/images/hero/lisboa.jpg",
    highlights: ["Miradouros", "Gastronomia", "Fado", "Acessivel"],
    bestTimeToVisit: "Marco a Outubro",
    averageDays: "3 a 5 dias",
    language: "Portugues",
    currency: "Euro (EUR)",
    attractions: [
      {
        id: "lis-1",
        name: "Torre de Belem",
        category: "Monumento",
        description: "Torre manuelina a beira do Tejo, simbolo dos Descobrimentos portugueses.",
        imageUrl: "/images/demo/lisboa/lis-001.jpg",
        priceLevel: 1,
        rating: 4.5,
        tags: ["patrimonio", "historia"],
      },
      {
        id: "lis-2",
        name: "Mosteiro dos Jeronimos",
        category: "Monumento",
        description: "Obra-prima do estilo manuelino e patrimonio mundial UNESCO.",
        imageUrl: "/images/demo/lisboa/lis-002.jpg",
        priceLevel: 1,
        rating: 4.7,
        tags: ["patrimonio", "arquitetura"],
      },
      {
        id: "lis-3",
        name: "Castelo de Sao Jorge",
        category: "Monumento",
        description: "Castelo mouro do seculo XI com vistas panoramicas sobre Lisboa.",
        imageUrl: "/images/demo/lisboa/lis-003.jpg",
        priceLevel: 2,
        rating: 4.4,
        tags: ["historia", "miradouro"],
      },
      {
        id: "lis-4",
        name: "Pasteis de Belem",
        category: "Gastronomia",
        description: "Pastelaria historica desde 1837, berco dos famosos pasteis de nata.",
        imageUrl: "/images/demo/lisboa/lis-005.jpg",
        priceLevel: 1,
        rating: 4.4,
        tags: ["gastronomia", "historico"],
      },
      {
        id: "lis-5",
        name: "Oceanario de Lisboa",
        category: "Museu",
        description: "Um dos maiores e melhores aquarios da Europa, otimo para familias.",
        imageUrl: "/images/demo/lisboa/lis-006.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["familia", "aquario"],
      },
      {
        id: "lis-6",
        name: "Bairro de Alfama",
        category: "Bairro",
        description: "Bairro mais antigo com ruelas medievais, casas de fado e miradouros.",
        imageUrl: "/images/demo/lisboa/lis-008.jpg",
        priceLevel: 0,
        rating: 4.5,
        tags: ["fado", "cultura", "gratuito"],
      },
      {
        id: "lis-7",
        name: "Elevador de Santa Justa",
        category: "Monumento",
        description: "Elevador neogotico de 1902 com plataforma panoramica.",
        imageUrl: "/images/demo/lisboa/lis-011.jpg",
        priceLevel: 1,
        rating: 4.2,
        tags: ["miradouro", "arquitetura"],
      },
      {
        id: "lis-8",
        name: "Time Out Market",
        category: "Gastronomia",
        description: "Mercado gastronomico com os melhores chefs de Lisboa.",
        imageUrl: "/images/demo/lisboa/lis-010.jpg",
        priceLevel: 2,
        rating: 4.3,
        tags: ["gastronomia", "mercado", "cultura"],
      },
    ],
  },
  barcelona: {
    slug: "barcelona",
    name: "Barcelona",
    country: "Espanha",
    description:
      "Capital da Catalunha que mistura praias mediterraneas com a arquitetura surrealista de Gaudi. Uma cidade vibrante onde arte, gastronomia e vida ao ar livre se encontram em cada esquina.",
    heroImage: "/images/hero/barcelona.jpg",
    highlights: ["Gaudi", "Praias", "Gastronomia", "Vida Noturna"],
    bestTimeToVisit: "Maio a Junho e Setembro a Outubro",
    averageDays: "3 a 5 dias",
    language: "Espanhol e Catalao",
    currency: "Euro (EUR)",
    attractions: [
      {
        id: "bcn-1",
        name: "Sagrada Familia",
        category: "Igreja",
        description: "Obra-prima inacabada de Gaudi, a basilica mais visitada da Europa.",
        imageUrl: "/images/demo/barcelona/bcn-001.jpg",
        priceLevel: 3,
        rating: 4.8,
        tags: ["gaudi", "icone", "arquitetura"],
      },
      {
        id: "bcn-2",
        name: "Parque Guell",
        category: "Parque",
        description: "Parque fantastico de Gaudi com mosaicos coloridos e vistas da cidade.",
        imageUrl: "/images/demo/barcelona/bcn-002.jpg",
        priceLevel: 2,
        rating: 4.5,
        tags: ["gaudi", "parque", "arte"],
      },
      {
        id: "bcn-3",
        name: "La Rambla",
        category: "Bairro",
        description: "Boulevard icoinico que conecta a Praca Catalunha ao porto.",
        imageUrl: "/images/demo/barcelona/bcn-003.jpg",
        priceLevel: 0,
        rating: 4.2,
        tags: ["passeio", "compras", "gratuito"],
      },
      {
        id: "bcn-4",
        name: "Casa Batllo",
        category: "Monumento",
        description: "Edificio modernista de Gaudi com fachada ondulante e interior fantastico.",
        imageUrl: "/images/demo/barcelona/bcn-004.jpg",
        priceLevel: 3,
        rating: 4.6,
        tags: ["gaudi", "arquitetura", "arte"],
      },
      {
        id: "bcn-5",
        name: "Bairro Gotico",
        category: "Bairro",
        description: "Centro historico medieval com catedral gotica e ruelas charmosas.",
        imageUrl: "/images/demo/barcelona/bcn-005.jpg",
        priceLevel: 0,
        rating: 4.4,
        tags: ["historia", "cultura", "gratuito"],
      },
      {
        id: "bcn-6",
        name: "Mercado La Boqueria",
        category: "Gastronomia",
        description: "Mercado centenario com frutas frescas, tapas e sabores catalanes.",
        imageUrl: "/images/demo/barcelona/bcn-006.jpg",
        priceLevel: 1,
        rating: 4.4,
        tags: ["gastronomia", "mercado"],
      },
      {
        id: "bcn-7",
        name: "Praia da Barceloneta",
        category: "Praia",
        description: "Praia urbana mais popular com calçadao, bares e esportes aquaticos.",
        imageUrl: "/images/demo/barcelona/bcn-007.jpg",
        priceLevel: 0,
        rating: 4.3,
        tags: ["praia", "familia", "gratuito"],
      },
      {
        id: "bcn-8",
        name: "Camp Nou (Spotify Camp Nou)",
        category: "Esporte",
        description: "Estadio do FC Barcelona com museu e tour pelo vestiario.",
        imageUrl: "/images/demo/barcelona/bcn-008.jpg",
        priceLevel: 2,
        rating: 4.5,
        tags: ["esporte", "futebol"],
      },
    ],
  },
  amsterdam: {
    slug: "amsterdam",
    name: "Amsterdam",
    country: "Holanda",
    description:
      "Cidade dos canais, bicicletas e museus extraordinarios. Amsterdam combina historia da Era de Ouro holandesa com uma atmosfera liberal e moderna, perfeita para explorar a pe ou de barco.",
    heroImage: "/images/hero/amsterdam.jpg",
    highlights: ["Canais", "Museus", "Bicicletas", "Tolerante"],
    bestTimeToVisit: "Abril a Setembro",
    averageDays: "3 a 4 dias",
    language: "Holandes",
    currency: "Euro (EUR)",
    attractions: [
      {
        id: "ams-1",
        name: "Rijksmuseum",
        category: "Museu",
        description: "Museu nacional com obras de Rembrandt, Vermeer e a Ronda Noturna.",
        imageUrl: "/images/demo/amsterdam/ams-001.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["arte", "historia", "cultura"],
      },
      {
        id: "ams-2",
        name: "Museu Van Gogh",
        category: "Museu",
        description: "Maior colecao do mundo de obras de Van Gogh, incluindo Os Girassois.",
        imageUrl: "/images/demo/amsterdam/ams-002.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["arte", "impressionismo"],
      },
      {
        id: "ams-3",
        name: "Casa de Anne Frank",
        category: "Museu",
        description: "Museu biografico no esconderijo onde Anne Frank escreveu seu diario.",
        imageUrl: "/images/demo/amsterdam/ams-003.jpg",
        priceLevel: 2,
        rating: 4.7,
        tags: ["historia", "memorial"],
      },
      {
        id: "ams-4",
        name: "Passeio de Barco pelos Canais",
        category: "Passeio",
        description: "Cruzeiro pelos canais patrimonio UNESCO com vistas das casas do seculo XVII.",
        imageUrl: "/images/demo/amsterdam/ams-004.jpg",
        priceLevel: 2,
        rating: 4.5,
        tags: ["canais", "passeio", "patrimonio"],
      },
      {
        id: "ams-5",
        name: "Vondelpark",
        category: "Parque",
        description: "Maior parque urbano de Amsterdam, perfeito para piquenique e descanso.",
        imageUrl: "/images/demo/amsterdam/ams-005.jpg",
        priceLevel: 0,
        rating: 4.5,
        tags: ["parque", "gratuito", "familia"],
      },
      {
        id: "ams-6",
        name: "Jordaan",
        category: "Bairro",
        description: "Bairro charmoso com galerias, cafes e lojas vintage ao longo dos canais.",
        imageUrl: "/images/demo/amsterdam/ams-006.jpg",
        priceLevel: 0,
        rating: 4.5,
        tags: ["bairro", "cultura", "gratuito"],
      },
      {
        id: "ams-7",
        name: "Mercado Albert Cuyp",
        category: "Gastronomia",
        description: "Maior mercado ao ar livre da Holanda com comidas tipicas e queijos.",
        imageUrl: "/images/demo/amsterdam/ams-007.jpg",
        priceLevel: 1,
        rating: 4.3,
        tags: ["gastronomia", "mercado"],
      },
      {
        id: "ams-8",
        name: "Praca Dam e Palacio Real",
        category: "Monumento",
        description: "Praca central com o Palacio Real e o Monumento Nacional.",
        imageUrl: "/images/demo/amsterdam/ams-008.jpg",
        priceLevel: 1,
        rating: 4.3,
        tags: ["historia", "praca"],
      },
    ],
  },
  praga: {
    slug: "praga",
    name: "Praga",
    country: "Republica Tcheca",
    description:
      "A cidade dos cem campanarios encanta com sua arquitetura medieval preservada, cerveja artesanal e precos acessiveis. O centro historico inteiro e patrimonio UNESCO, com pontes, castelos e pracas de conto de fadas.",
    heroImage: "/images/hero/praga.jpg",
    highlights: ["Medieval", "Cerveja", "Acessivel", "Arquitetura"],
    bestTimeToVisit: "Maio a Setembro",
    averageDays: "3 a 4 dias",
    language: "Tcheco",
    currency: "Coroa Tcheca (CZK)",
    attractions: [
      {
        id: "prg-1",
        name: "Ponte Carlos",
        category: "Monumento",
        description: "Ponte gotica do seculo XIV com 30 estatuas barrocas e vistas do castelo.",
        imageUrl: "/images/demo/praga/prg-001.jpg",
        priceLevel: 0,
        rating: 4.7,
        tags: ["icone", "gotico", "gratuito"],
      },
      {
        id: "prg-2",
        name: "Castelo de Praga",
        category: "Castelo",
        description: "Maior complexo de castelo antigo do mundo com catedral e palacios.",
        imageUrl: "/images/demo/praga/prg-002.jpg",
        priceLevel: 2,
        rating: 4.6,
        tags: ["castelo", "historia", "patrimonio"],
      },
      {
        id: "prg-3",
        name: "Praca da Cidade Velha",
        category: "Praca",
        description: "Praca medieval com o Relogio Astronomico e igrejas goticas.",
        imageUrl: "/images/demo/praga/prg-003.jpg",
        priceLevel: 0,
        rating: 4.7,
        tags: ["praca", "medieval", "gratuito"],
      },
      {
        id: "prg-4",
        name: "Relogio Astronomico",
        category: "Monumento",
        description: "Relogio medieval de 1410 com espetaculo de apostolos a cada hora.",
        imageUrl: "/images/demo/praga/prg-004.jpg",
        priceLevel: 1,
        rating: 4.4,
        tags: ["medieval", "icone"],
      },
      {
        id: "prg-5",
        name: "Bairro Judeu (Josefov)",
        category: "Bairro",
        description: "Gueto historico com sinagogas, cemiterio antigo e museu judaico.",
        imageUrl: "/images/demo/praga/prg-005.jpg",
        priceLevel: 2,
        rating: 4.5,
        tags: ["historia", "cultura", "memorial"],
      },
      {
        id: "prg-6",
        name: "Petrin Hill",
        category: "Parque",
        description: "Colina com torre de observacao, jardins e vista panoramica da cidade.",
        imageUrl: "/images/demo/praga/prg-006.jpg",
        priceLevel: 1,
        rating: 4.5,
        tags: ["parque", "miradouro", "familia"],
      },
      {
        id: "prg-7",
        name: "Cervejaria U Fleku",
        category: "Gastronomia",
        description: "Cervejaria mais antiga de Praga (desde 1499) com cerveja escura propria.",
        imageUrl: "/images/demo/praga/prg-007.jpg",
        priceLevel: 1,
        rating: 4.3,
        tags: ["cerveja", "gastronomia", "historico"],
      },
      {
        id: "prg-8",
        name: "Muro de John Lennon",
        category: "Arte",
        description: "Muro coberto de grafites inspirados em Lennon e mensagens de paz.",
        imageUrl: "/images/demo/praga/prg-008.jpg",
        priceLevel: 0,
        rating: 4.2,
        tags: ["arte", "cultura", "gratuito"],
      },
    ],
  },
};
