import { FlightSearchResult, FlightOffer } from "@/types";

function createFlightOffer(params: {
  id: string;
  airline: string;
  pricePerPerson: number;
  outDepartureAirport: string;
  outArrivalAirport: string;
  outDepartureTime: string;
  outArrivalTime: string;
  outDurationMinutes: number;
  outStops: number;
  outStopDetails?: { airport: string; city: string; durationMinutes: number }[];
  inDepartureAirport?: string;
  inArrivalAirport?: string;
  inDepartureTime?: string;
  inArrivalTime?: string;
  inDurationMinutes?: number;
  inStops?: number;
  inStopDetails?: { airport: string; city: string; durationMinutes: number }[];
  baggageIncluded: boolean;
}): FlightOffer {
  return {
    id: params.id,
    airline: params.airline,
    totalPrice: params.pricePerPerson * 2,
    pricePerPerson: params.pricePerPerson,
    currency: "BRL",
    outbound: {
      departureAirport: params.outDepartureAirport,
      arrivalAirport: params.outArrivalAirport,
      departureTime: params.outDepartureTime,
      arrivalTime: params.outArrivalTime,
      durationMinutes: params.outDurationMinutes,
      stops: params.outStops,
      stopDetails: params.outStopDetails || [],
    },
    inbound: params.inDepartureAirport
      ? {
          departureAirport: params.inDepartureAirport,
          arrivalAirport: params.inArrivalAirport!,
          departureTime: params.inDepartureTime!,
          arrivalTime: params.inArrivalTime!,
          durationMinutes: params.inDurationMinutes!,
          stops: params.inStops || 0,
          stopDetails: params.inStopDetails || [],
        }
      : undefined,
    baggageIncluded: params.baggageIncluded,
    lastUpdatedAt: "2025-01-15T10:00:00Z",
  };
}

export const DEMO_FLIGHTS_VIX_LIS: FlightSearchResult = {
  offers: [
    createFlightOffer({
      id: "vix-lis-001",
      airline: "TAP Portugal",
      pricePerPerson: 4250,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T22:30:00",
      outArrivalTime: "2025-06-16T10:45:00",
      outDurationMinutes: 615,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 135 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T11:00:00",
      inArrivalTime: "2025-06-26T19:30:00",
      inDurationMinutes: 690,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 180 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "vix-lis-002",
      airline: "LATAM",
      pricePerPerson: 3850,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T18:00:00",
      outArrivalTime: "2025-06-16T11:30:00",
      outDurationMinutes: 750,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 210 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T14:20:00",
      inArrivalTime: "2025-06-27T00:50:00",
      inDurationMinutes: 750,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 210 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "vix-lis-003",
      airline: "Air France",
      pricePerPerson: 5100,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T15:20:00",
      outArrivalTime: "2025-06-16T12:10:00",
      outDurationMinutes: 930,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 120 },
        { airport: "CDG", city: "Paris", durationMinutes: 150 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T08:30:00",
      inArrivalTime: "2025-06-26T22:45:00",
      inDurationMinutes: 975,
      inStops: 2,
      inStopDetails: [
        { airport: "CDG", city: "Paris", durationMinutes: 135 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 180 },
      ],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "vix-lis-004",
      airline: "Azul",
      pricePerPerson: 3650,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T20:45:00",
      outArrivalTime: "2025-06-16T09:15:00",
      outDurationMinutes: 630,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 120 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T12:30:00",
      inArrivalTime: "2025-06-26T21:00:00",
      inDurationMinutes: 690,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 150 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "vix-lis-005",
      airline: "KLM",
      pricePerPerson: 5650,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T14:00:00",
      outArrivalTime: "2025-06-16T13:30:00",
      outDurationMinutes: 1050,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 150 },
        { airport: "AMS", city: "Amsterdam", durationMinutes: 180 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T07:00:00",
      inArrivalTime: "2025-06-26T23:30:00",
      inDurationMinutes: 1110,
      inStops: 2,
      inStopDetails: [
        { airport: "AMS", city: "Amsterdam", durationMinutes: 165 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 195 },
      ],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "vix-lis-006",
      airline: "Iberia",
      pricePerPerson: 4800,
      outDepartureAirport: "VIX",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T16:30:00",
      outArrivalTime: "2025-06-16T11:00:00",
      outDurationMinutes: 870,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 140 },
        { airport: "MAD", city: "Madrid", durationMinutes: 90 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "VIX",
      inDepartureTime: "2025-06-26T09:45:00",
      inArrivalTime: "2025-06-26T22:00:00",
      inDurationMinutes: 855,
      inStops: 2,
      inStopDetails: [
        { airport: "MAD", city: "Madrid", durationMinutes: 75 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 150 },
      ],
      baggageIncluded: true,
    }),
  ],
  provider: "mock",
  searchedAt: "2025-01-15T10:00:00Z",
  isDemo: true,
  metadata: { totalFound: 6 },
};

export const DEMO_FLIGHTS_GIG_LIS: FlightSearchResult = {
  offers: [
    createFlightOffer({
      id: "gig-lis-001",
      airline: "TAP Portugal",
      pricePerPerson: 3900,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T23:00:00",
      outArrivalTime: "2025-06-16T10:30:00",
      outDurationMinutes: 570,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T11:30:00",
      inArrivalTime: "2025-06-26T18:00:00",
      inDurationMinutes: 570,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gig-lis-002",
      airline: "LATAM",
      pricePerPerson: 3600,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T21:30:00",
      outArrivalTime: "2025-06-16T09:15:00",
      outDurationMinutes: 585,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T13:00:00",
      inArrivalTime: "2025-06-26T19:45:00",
      inDurationMinutes: 585,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gig-lis-003",
      airline: "Azul",
      pricePerPerson: 3500,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T22:15:00",
      outArrivalTime: "2025-06-16T09:50:00",
      outDurationMinutes: 575,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T10:00:00",
      inArrivalTime: "2025-06-26T16:40:00",
      inDurationMinutes: 580,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gig-lis-004",
      airline: "Air France",
      pricePerPerson: 4700,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T19:00:00",
      outArrivalTime: "2025-06-16T12:30:00",
      outDurationMinutes: 870,
      outStops: 1,
      outStopDetails: [{ airport: "CDG", city: "Paris", durationMinutes: 150 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T08:00:00",
      inArrivalTime: "2025-06-26T19:30:00",
      inDurationMinutes: 870,
      inStops: 1,
      inStopDetails: [{ airport: "CDG", city: "Paris", durationMinutes: 150 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gig-lis-005",
      airline: "Lufthansa",
      pricePerPerson: 5200,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T17:30:00",
      outArrivalTime: "2025-06-16T13:00:00",
      outDurationMinutes: 990,
      outStops: 1,
      outStopDetails: [{ airport: "FRA", city: "Frankfurt", durationMinutes: 180 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T07:30:00",
      inArrivalTime: "2025-06-26T20:00:00",
      inDurationMinutes: 930,
      inStops: 1,
      inStopDetails: [{ airport: "FRA", city: "Frankfurt", durationMinutes: 150 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gig-lis-006",
      airline: "TAP Portugal",
      pricePerPerson: 7500,
      outDepartureAirport: "GIG",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T22:50:00",
      outArrivalTime: "2025-06-16T10:20:00",
      outDurationMinutes: 570,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GIG",
      inDepartureTime: "2025-06-26T11:00:00",
      inArrivalTime: "2025-06-26T17:30:00",
      inDurationMinutes: 570,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
  ],
  provider: "mock",
  searchedAt: "2025-01-15T10:00:00Z",
  isDemo: true,
  metadata: { totalFound: 6 },
};

export const DEMO_FLIGHTS_GRU_LIS: FlightSearchResult = {
  offers: [
    createFlightOffer({
      id: "gru-lis-001",
      airline: "TAP Portugal",
      pricePerPerson: 3700,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T23:15:00",
      outArrivalTime: "2025-06-16T10:00:00",
      outDurationMinutes: 525,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T12:00:00",
      inArrivalTime: "2025-06-26T18:15:00",
      inDurationMinutes: 555,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-002",
      airline: "LATAM",
      pricePerPerson: 3500,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T22:00:00",
      outArrivalTime: "2025-06-16T09:00:00",
      outDurationMinutes: 540,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T13:30:00",
      inArrivalTime: "2025-06-26T19:45:00",
      inDurationMinutes: 555,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-003",
      airline: "Azul",
      pricePerPerson: 3550,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T21:45:00",
      outArrivalTime: "2025-06-16T08:45:00",
      outDurationMinutes: 540,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T10:30:00",
      inArrivalTime: "2025-06-26T16:45:00",
      inDurationMinutes: 555,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-004",
      airline: "Iberia",
      pricePerPerson: 4100,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T20:00:00",
      outArrivalTime: "2025-06-16T11:30:00",
      outDurationMinutes: 810,
      outStops: 1,
      outStopDetails: [{ airport: "MAD", city: "Madrid", durationMinutes: 105 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T09:00:00",
      inArrivalTime: "2025-06-26T19:00:00",
      inDurationMinutes: 840,
      inStops: 1,
      inStopDetails: [{ airport: "MAD", city: "Madrid", durationMinutes: 120 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-005",
      airline: "Lufthansa",
      pricePerPerson: 4900,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T18:30:00",
      outArrivalTime: "2025-06-16T13:00:00",
      outDurationMinutes: 930,
      outStops: 1,
      outStopDetails: [{ airport: "FRA", city: "Frankfurt", durationMinutes: 165 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T07:00:00",
      inArrivalTime: "2025-06-26T18:30:00",
      inDurationMinutes: 930,
      inStops: 1,
      inStopDetails: [{ airport: "FRA", city: "Frankfurt", durationMinutes: 165 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-006",
      airline: "KLM",
      pricePerPerson: 5300,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T17:00:00",
      outArrivalTime: "2025-06-16T14:00:00",
      outDurationMinutes: 1020,
      outStops: 1,
      outStopDetails: [{ airport: "AMS", city: "Amsterdam", durationMinutes: 195 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T06:30:00",
      inArrivalTime: "2025-06-26T18:00:00",
      inDurationMinutes: 930,
      inStops: 1,
      inStopDetails: [{ airport: "AMS", city: "Amsterdam", durationMinutes: 180 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "gru-lis-007",
      airline: "TAP Portugal",
      pricePerPerson: 7200,
      outDepartureAirport: "GRU",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T22:45:00",
      outArrivalTime: "2025-06-16T09:30:00",
      outDurationMinutes: 525,
      outStops: 0,
      outStopDetails: [],
      inDepartureAirport: "LIS",
      inArrivalAirport: "GRU",
      inDepartureTime: "2025-06-26T11:00:00",
      inArrivalTime: "2025-06-26T17:15:00",
      inDurationMinutes: 555,
      inStops: 0,
      inStopDetails: [],
      baggageIncluded: true,
    }),
  ],
  provider: "mock",
  searchedAt: "2025-01-15T10:00:00Z",
  isDemo: true,
  metadata: { totalFound: 7 },
};

export const DEMO_FLIGHTS_CNF_LIS: FlightSearchResult = {
  offers: [
    createFlightOffer({
      id: "cnf-lis-001",
      airline: "TAP Portugal",
      pricePerPerson: 4100,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T19:30:00",
      outArrivalTime: "2025-06-16T10:30:00",
      outDurationMinutes: 660,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 120 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T11:00:00",
      inArrivalTime: "2025-06-26T20:00:00",
      inDurationMinutes: 720,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 150 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "cnf-lis-002",
      airline: "LATAM",
      pricePerPerson: 3800,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T18:00:00",
      outArrivalTime: "2025-06-16T09:30:00",
      outDurationMinutes: 690,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 150 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T13:00:00",
      inArrivalTime: "2025-06-26T22:30:00",
      inDurationMinutes: 750,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 180 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "cnf-lis-003",
      airline: "Azul",
      pricePerPerson: 3650,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T20:00:00",
      outArrivalTime: "2025-06-16T09:00:00",
      outDurationMinutes: 660,
      outStops: 1,
      outStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 120 }],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T10:30:00",
      inArrivalTime: "2025-06-26T19:30:00",
      inDurationMinutes: 720,
      inStops: 1,
      inStopDetails: [{ airport: "GRU", city: "São Paulo", durationMinutes: 150 }],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "cnf-lis-004",
      airline: "Air France",
      pricePerPerson: 5400,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T15:00:00",
      outArrivalTime: "2025-06-16T12:00:00",
      outDurationMinutes: 1020,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 120 },
        { airport: "CDG", city: "Paris", durationMinutes: 135 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T08:00:00",
      inArrivalTime: "2025-06-26T23:00:00",
      inDurationMinutes: 1080,
      inStops: 2,
      inStopDetails: [
        { airport: "CDG", city: "Paris", durationMinutes: 150 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 165 },
      ],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "cnf-lis-005",
      airline: "Iberia",
      pricePerPerson: 4600,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T16:30:00",
      outArrivalTime: "2025-06-16T11:45:00",
      outDurationMinutes: 915,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 130 },
        { airport: "MAD", city: "Madrid", durationMinutes: 90 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T09:00:00",
      inArrivalTime: "2025-06-26T22:00:00",
      inDurationMinutes: 960,
      inStops: 2,
      inStopDetails: [
        { airport: "MAD", city: "Madrid", durationMinutes: 80 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 180 },
      ],
      baggageIncluded: true,
    }),
    createFlightOffer({
      id: "cnf-lis-006",
      airline: "Lufthansa",
      pricePerPerson: 5800,
      outDepartureAirport: "CNF",
      outArrivalAirport: "LIS",
      outDepartureTime: "2025-06-15T14:00:00",
      outArrivalTime: "2025-06-16T13:30:00",
      outDurationMinutes: 1170,
      outStops: 2,
      outStopDetails: [
        { airport: "GRU", city: "São Paulo", durationMinutes: 150 },
        { airport: "FRA", city: "Frankfurt", durationMinutes: 195 },
      ],
      inDepartureAirport: "LIS",
      inArrivalAirport: "CNF",
      inDepartureTime: "2025-06-26T07:00:00",
      inArrivalTime: "2025-06-26T23:30:00",
      inDurationMinutes: 1170,
      inStops: 2,
      inStopDetails: [
        { airport: "FRA", city: "Frankfurt", durationMinutes: 180 },
        { airport: "GRU", city: "São Paulo", durationMinutes: 165 },
      ],
      baggageIncluded: true,
    }),
  ],
  provider: "mock",
  searchedAt: "2025-01-15T10:00:00Z",
  isDemo: true,
  metadata: { totalFound: 6 },
};

export function getDemoFlights(
  origin: string
): FlightSearchResult | undefined {
  const routeMap: Record<string, FlightSearchResult> = {
    VIX: DEMO_FLIGHTS_VIX_LIS,
    GIG: DEMO_FLIGHTS_GIG_LIS,
    GRU: DEMO_FLIGHTS_GRU_LIS,
    CNF: DEMO_FLIGHTS_CNF_LIS,
  };
  return routeMap[origin.toUpperCase()];
}
