import { Attraction } from "@/types";

export const DEMO_ATTRACTIONS: Record<string, Attraction[]> = {
  Lisboa: [
    {
      id: "lis-001",
      name: "Torre de Belém",
      category: "monumento",
      description: "Torre manuelina à beira do Tejo, símbolo dos Descobrimentos portugueses e patrimônio UNESCO.",
      address: "Av. Brasília, 1400-038 Lisboa",
      latitude: 38.6916,
      longitude: -9.2159,
      rating: 4.5,
      totalRatings: 48320,
      imageUrl: "/images/demo/lisboa/lis-001.jpg",
      priceLevel: 1,
      types: ["monumento", "patrimônio", "história"],
    },
    {
      id: "lis-002",
      name: "Mosteiro dos Jerónimos",
      category: "monumento",
      description: "Obra-prima do estilo manuelino, um dos mais belos mosteiros da Europa e patrimônio mundial.",
      address: "Praça do Império, 1400-206 Lisboa",
      latitude: 38.6979,
      longitude: -9.2068,
      rating: 4.7,
      totalRatings: 52140,
      imageUrl: "/images/demo/lisboa/lis-002.jpg",
      priceLevel: 1,
      types: ["monumento", "patrimônio", "religião", "arquitetura"],
    },
    {
      id: "lis-003",
      name: "Castelo de São Jorge",
      category: "monumento",
      description: "Castelo mouro do século XI com vistas panorâmicas sobre Lisboa e o rio Tejo.",
      address: "R. de Santa Cruz do Castelo, 1100-129 Lisboa",
      latitude: 38.7139,
      longitude: -9.1334,
      rating: 4.4,
      totalRatings: 38750,
      imageUrl: "/images/demo/lisboa/lis-003.jpg",
      priceLevel: 2,
      types: ["monumento", "história", "miradouro"],
    },
    {
      id: "lis-004",
      name: "Museu Nacional do Azulejo",
      category: "museu",
      description: "Museu único dedicado à arte do azulejo português, desde o século XV até obras contemporâneas.",
      address: "R. da Madre de Deus 4, 1900-312 Lisboa",
      latitude: 38.7249,
      longitude: -9.1141,
      rating: 4.6,
      totalRatings: 12430,
      imageUrl: "/images/demo/lisboa/lis-004.jpg",
      priceLevel: 1,
      types: ["museu", "arte", "cultura"],
    },
    {
      id: "lis-005",
      name: "Pastéis de Belém",
      category: "restaurante",
      description: "Pastelaria histórica desde 1837, berço dos famosos pastéis de nata com receita secreta.",
      address: "R. de Belém 84-92, 1300-085 Lisboa",
      latitude: 38.6975,
      longitude: -9.2030,
      rating: 4.4,
      totalRatings: 67820,
      imageUrl: "/images/demo/lisboa/lis-005.jpg",
      priceLevel: 1,
      types: ["restaurante", "gastronomia", "histórico"],
    },
    {
      id: "lis-006",
      name: "Oceanário de Lisboa",
      category: "museu",
      description: "Um dos maiores e melhores aquários da Europa, com oceanos de todo o mundo representados.",
      address: "Esplanada Dom Carlos I, 1990-005 Lisboa",
      latitude: 38.7636,
      longitude: -9.0937,
      rating: 4.7,
      totalRatings: 42150,
      imageUrl: "/images/demo/lisboa/lis-006.jpg",
      priceLevel: 2,
      types: ["museu", "aquário", "família"],
    },
    {
      id: "lis-007",
      name: "Praça do Comércio",
      category: "monumento",
      description: "Grande praça ribeirinha com arco triunfal, terraços e vista ampla para o Tejo.",
      address: "Praça do Comércio, 1100-148 Lisboa",
      latitude: 38.7075,
      longitude: -9.1364,
      rating: 4.6,
      totalRatings: 35280,
      imageUrl: "/images/demo/lisboa/lis-007.jpg",
      priceLevel: 0,
      types: ["praça", "história", "arquitetura"],
    },
    {
      id: "lis-008",
      name: "Bairro de Alfama",
      category: "monumento",
      description: "Bairro mais antigo de Lisboa com ruelas medievais, casas de fado e miradouros encantadores.",
      address: "Alfama, Lisboa",
      latitude: 38.7114,
      longitude: -9.1304,
      rating: 4.5,
      totalRatings: 28940,
      imageUrl: "/images/demo/lisboa/lis-008.jpg",
      priceLevel: 0,
      types: ["bairro", "cultura", "fado", "história"],
    },
    {
      id: "lis-009",
      name: "Palácio Nacional de Sintra",
      category: "monumento",
      description: "Palácio real medieval com chaminés cônicas icônicas e azulejos hispano-árabes.",
      address: "Largo Rainha Dona Amélia, 2710-616 Sintra",
      latitude: 38.7976,
      longitude: -9.3907,
      rating: 4.4,
      totalRatings: 15620,
      imageUrl: "/images/demo/lisboa/lis-009.jpg",
      priceLevel: 2,
      types: ["palácio", "patrimônio", "história"],
    },
    {
      id: "lis-010",
      name: "Mercado da Ribeira (Time Out Market)",
      category: "mercado",
      description: "Mercado gastronômico com os melhores chefs de Lisboa reunidos sob um teto histórico.",
      address: "Av. 24 de Julho 49, 1200-479 Lisboa",
      latitude: 38.7069,
      longitude: -9.1457,
      rating: 4.3,
      totalRatings: 31540,
      imageUrl: "/images/demo/lisboa/lis-010.jpg",
      priceLevel: 2,
      types: ["mercado", "gastronomia", "cultura"],
    },
    {
      id: "lis-011",
      name: "Elevador de Santa Justa",
      category: "monumento",
      description: "Elevador neogótico de 1902 com plataforma panorâmica e vista sobre a Baixa e o Castelo.",
      address: "R. do Ouro, 1150-060 Lisboa",
      latitude: 38.7121,
      longitude: -9.1393,
      rating: 4.2,
      totalRatings: 22310,
      imageUrl: "/images/demo/lisboa/lis-011.jpg",
      priceLevel: 1,
      types: ["monumento", "miradouro", "arquitetura"],
    },
    {
      id: "lis-012",
      name: "Palácio da Pena (Sintra)",
      category: "monumento",
      description: "Palácio romântico colorido no topo da serra de Sintra, patrimônio mundial UNESCO.",
      address: "Estrada da Pena, 2710-609 Sintra",
      latitude: 38.7876,
      longitude: -9.3907,
      rating: 4.6,
      totalRatings: 41230,
      imageUrl: "/images/demo/lisboa/lis-012.jpg",
      priceLevel: 2,
      types: ["palácio", "patrimônio", "jardins", "arquitetura"],
    },
  ],
  Paris: [
    {
      id: "par-001",
      name: "Torre Eiffel",
      category: "monumento",
      description: "Símbolo máximo de Paris e da França, com vistas panorâmicas de 360° da Cidade Luz.",
      address: "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
      latitude: 48.8584,
      longitude: 2.2945,
      rating: 4.6,
      totalRatings: 234500,
      imageUrl: "/images/demo/paris/par-001.jpg",
      priceLevel: 2,
      types: ["monumento", "miradouro", "ícone"],
    },
    {
      id: "par-002",
      name: "Museu do Louvre",
      category: "museu",
      description: "Maior e mais visitado museu de arte do mundo, lar da Mona Lisa e 35.000 obras-primas.",
      address: "Rue de Rivoli, 75001 Paris",
      latitude: 48.8606,
      longitude: 2.3376,
      rating: 4.7,
      totalRatings: 198320,
      imageUrl: "/images/demo/paris/par-002.jpg",
      priceLevel: 2,
      types: ["museu", "arte", "história"],
    },
    {
      id: "par-003",
      name: "Sacré-Cœur e Montmartre",
      category: "igreja",
      description: "Basílica branca no ponto mais alto de Paris, com bairro artístico de ruas charmosas.",
      address: "35 Rue du Chevalier de la Barre, 75018 Paris",
      latitude: 48.8867,
      longitude: 2.3431,
      rating: 4.6,
      totalRatings: 87650,
      imageUrl: "/images/demo/paris/par-003.jpg",
      priceLevel: 0,
      types: ["igreja", "bairro", "arte", "miradouro"],
    },
    {
      id: "par-004",
      name: "Arco do Triunfo",
      category: "monumento",
      description: "Monumento neoclássico com vista para os Champs-Élysées e 12 avenidas radiantes.",
      address: "Place Charles de Gaulle, 75008 Paris",
      latitude: 48.8738,
      longitude: 2.2950,
      rating: 4.6,
      totalRatings: 72140,
      imageUrl: "/images/demo/paris/par-004.jpg",
      priceLevel: 2,
      types: ["monumento", "história", "miradouro"],
    },
    {
      id: "par-005",
      name: "Catedral Notre-Dame",
      category: "igreja",
      description: "Obra-prima gótica do século XII, reaberta após restauração do incêndio de 2019.",
      address: "6 Parvis Notre-Dame, 75004 Paris",
      latitude: 48.8530,
      longitude: 2.3499,
      rating: 4.7,
      totalRatings: 112430,
      imageUrl: "/images/demo/paris/par-005.jpg",
      priceLevel: 0,
      types: ["igreja", "patrimônio", "gótico", "arquitetura"],
    },
    {
      id: "par-006",
      name: "Museu d'Orsay",
      category: "museu",
      description: "Museu impressionista numa antiga estação ferroviária com Monet, Renoir, Van Gogh e Degas.",
      address: "1 Rue de la Légion d'Honneur, 75007 Paris",
      latitude: 48.8600,
      longitude: 2.3266,
      rating: 4.7,
      totalRatings: 65430,
      imageUrl: "/images/demo/paris/par-006.jpg",
      priceLevel: 2,
      types: ["museu", "arte", "impressionismo"],
    },
    {
      id: "par-007",
      name: "Palácio de Versalhes",
      category: "monumento",
      description: "Residência real com Salão dos Espelhos, jardins geométricos e fontes monumentais.",
      address: "Place d'Armes, 78000 Versailles",
      latitude: 48.8049,
      longitude: 2.1204,
      rating: 4.5,
      totalRatings: 89340,
      imageUrl: "/images/demo/paris/par-007.jpg",
      priceLevel: 3,
      types: ["palácio", "jardins", "patrimônio", "história"],
    },
    {
      id: "par-008",
      name: "Jardim de Luxemburgo",
      category: "parque",
      description: "Jardim elegante com fontes, estátuas, Senado francês e áreas para descanso e piquenique.",
      address: "75006 Paris",
      latitude: 48.8462,
      longitude: 2.3372,
      rating: 4.6,
      totalRatings: 45210,
      imageUrl: "/images/demo/paris/par-008.jpg",
      priceLevel: 0,
      types: ["parque", "jardim", "lazer"],
    },
    {
      id: "par-009",
      name: "Quartier Latin",
      category: "monumento",
      description: "Bairro universitário histórico com livrarias, bistrôs, Panteão e atmosfera intelectual.",
      address: "Quartier Latin, 75005 Paris",
      latitude: 48.8498,
      longitude: 2.3447,
      rating: 4.4,
      totalRatings: 18920,
      imageUrl: "/images/demo/paris/par-009.jpg",
      priceLevel: 1,
      types: ["bairro", "cultura", "gastronomia", "história"],
    },
    {
      id: "par-010",
      name: "Cruzeiro pelo Rio Sena",
      category: "monumento",
      description: "Passeio de barco de 1 hora pelos principais monumentos parisienses vistos da água.",
      address: "Port de la Bourdonnais, 75007 Paris",
      latitude: 48.8600,
      longitude: 2.2900,
      rating: 4.5,
      totalRatings: 34560,
      imageUrl: "/images/demo/paris/par-010.jpg",
      priceLevel: 2,
      types: ["passeio", "barco", "turismo"],
    },
    {
      id: "par-011",
      name: "Champs-Élysées",
      category: "monumento",
      description: "A avenida mais famosa do mundo com lojas de luxo, cafés e cinemas.",
      address: "Av. des Champs-Élysées, 75008 Paris",
      latitude: 48.8698,
      longitude: 2.3075,
      rating: 4.4,
      totalRatings: 56780,
      imageUrl: "/images/demo/paris/par-011.jpg",
      priceLevel: 3,
      types: ["avenida", "compras", "cultura"],
    },
    {
      id: "par-012",
      name: "Le Marais",
      category: "monumento",
      description: "Bairro histórico com mansões medievais, galerias de arte, brechós e vida noturna.",
      address: "Le Marais, 75004 Paris",
      latitude: 48.8566,
      longitude: 2.3622,
      rating: 4.5,
      totalRatings: 23450,
      imageUrl: "/images/demo/paris/par-012.jpg",
      priceLevel: 2,
      types: ["bairro", "cultura", "compras", "gastronomia"],
    },
  ],
  Roma: [
    {
      id: "rom-001",
      name: "Coliseu",
      category: "monumento",
      description: "Anfiteatro romano do século I d.C., maior já construído, palco de lutas de gladiadores.",
      address: "Piazza del Colosseo, 1, 00184 Roma",
      latitude: 41.8902,
      longitude: 12.4922,
      rating: 4.7,
      totalRatings: 178430,
      imageUrl: "/images/demo/roma/rom-001.jpg",
      priceLevel: 2,
      types: ["monumento", "arqueologia", "história"],
    },
    {
      id: "rom-002",
      name: "Museus do Vaticano",
      category: "museu",
      description: "Coleção papal com obras de Michelangelo na Capela Sistina, Rafael e séculos de arte sacra.",
      address: "Viale Vaticano, 00165 Roma",
      latitude: 41.9065,
      longitude: 12.4536,
      rating: 4.6,
      totalRatings: 142560,
      imageUrl: "/images/demo/roma/rom-002.jpg",
      priceLevel: 3,
      types: ["museu", "arte", "religião", "patrimônio"],
    },
    {
      id: "rom-003",
      name: "Basílica de São Pedro",
      category: "igreja",
      description: "Maior igreja católica do mundo com a Pietà de Michelangelo e cúpula projetada por ele.",
      address: "Piazza San Pietro, 00120 Città del Vaticano",
      latitude: 41.9022,
      longitude: 12.4539,
      rating: 4.8,
      totalRatings: 156780,
      imageUrl: "/images/demo/roma/rom-003.jpg",
      priceLevel: 0,
      types: ["igreja", "arte", "arquitetura", "religião"],
    },
    {
      id: "rom-004",
      name: "Fontana di Trevi",
      category: "monumento",
      description: "Fonte barroca monumental do século XVIII - jogue uma moeda para garantir seu retorno a Roma.",
      address: "Piazza di Trevi, 00187 Roma",
      latitude: 41.9009,
      longitude: 12.4833,
      rating: 4.6,
      totalRatings: 134250,
      imageUrl: "/images/demo/roma/rom-004.jpg",
      priceLevel: 0,
      types: ["monumento", "fonte", "barroco"],
    },
    {
      id: "rom-005",
      name: "Panteão",
      category: "monumento",
      description: "Templo romano de 2000 anos com a maior cúpula de concreto não armado do mundo.",
      address: "Piazza della Rotonda, 00186 Roma",
      latitude: 41.8986,
      longitude: 12.4769,
      rating: 4.7,
      totalRatings: 98430,
      imageUrl: "/images/demo/roma/rom-005.jpg",
      priceLevel: 1,
      types: ["monumento", "templo", "arquitetura", "história"],
    },
    {
      id: "rom-006",
      name: "Fórum Romano",
      category: "monumento",
      description: "Centro político e religioso da Roma Antiga com templos, arcos triunfais e ruínas imperiais.",
      address: "Via della Salara Vecchia, 5/6, 00186 Roma",
      latitude: 41.8925,
      longitude: 12.4853,
      rating: 4.6,
      totalRatings: 72340,
      imageUrl: "/images/demo/roma/rom-006.jpg",
      priceLevel: 2,
      types: ["arqueologia", "história", "monumento"],
    },
    {
      id: "rom-007",
      name: "Trastevere",
      category: "monumento",
      description: "Bairro boêmio com trattorias autênticas, ruas de paralelepípedo, igrejas medievais e vida noturna.",
      address: "Trastevere, Roma",
      latitude: 41.8895,
      longitude: 12.4699,
      rating: 4.5,
      totalRatings: 28950,
      imageUrl: "/images/demo/roma/rom-007.jpg",
      priceLevel: 1,
      types: ["bairro", "gastronomia", "cultura", "vida noturna"],
    },
    {
      id: "rom-008",
      name: "Piazza Navona",
      category: "monumento",
      description: "Praça barroca com três fontes de Bernini, artistas de rua e cafés com mesas ao ar livre.",
      address: "Piazza Navona, 00186 Roma",
      latitude: 41.8992,
      longitude: 12.4731,
      rating: 4.5,
      totalRatings: 67890,
      imageUrl: "/images/demo/roma/rom-008.jpg",
      priceLevel: 0,
      types: ["praça", "arte", "barroco"],
    },
    {
      id: "rom-009",
      name: "Villa Borghese",
      category: "parque",
      description: "Grande parque com galeria de arte (Bernini, Caravaggio), jardins, lago e aluguel de bicicletas.",
      address: "Piazzale Napoleone I, 00197 Roma",
      latitude: 41.9145,
      longitude: 12.4855,
      rating: 4.5,
      totalRatings: 34520,
      imageUrl: "/images/demo/roma/rom-009.jpg",
      priceLevel: 1,
      types: ["parque", "museu", "arte", "lazer"],
    },
    {
      id: "rom-010",
      name: "Escadaria da Praça de Espanha",
      category: "monumento",
      description: "Escadaria monumental do século XVIII ligando a praça à igreja Trinità dei Monti.",
      address: "Piazza di Spagna, 00187 Roma",
      latitude: 41.9060,
      longitude: 12.4823,
      rating: 4.4,
      totalRatings: 56780,
      imageUrl: "/images/demo/roma/rom-010.jpg",
      priceLevel: 0,
      types: ["monumento", "praça", "compras"],
    },
    {
      id: "rom-011",
      name: "Castel Sant'Angelo",
      category: "monumento",
      description: "Antigo mausoléu imperial e fortaleza papal com terraço panorâmico sobre Roma.",
      address: "Lungotevere Castello, 50, 00193 Roma",
      latitude: 41.9031,
      longitude: 12.4663,
      rating: 4.5,
      totalRatings: 42310,
      imageUrl: "/images/demo/roma/rom-011.jpg",
      priceLevel: 2,
      types: ["monumento", "museu", "história"],
    },
    {
      id: "rom-012",
      name: "Campo de' Fiori",
      category: "mercado",
      description: "Praça com mercado matinal de flores e alimentos, transformando-se em polo gastronômico à noite.",
      address: "Campo de' Fiori, 00186 Roma",
      latitude: 41.8956,
      longitude: 12.4722,
      rating: 4.3,
      totalRatings: 23450,
      imageUrl: "/images/demo/roma/rom-012.jpg",
      priceLevel: 1,
      types: ["mercado", "gastronomia", "praça"],
    },
  ],
};
