import { TripPreferences, GeneratedItinerary } from "@/types";

export const DEMO_TRIP_PREFERENCES: TripPreferences = {
  startDate: "2025-06-15",
  endDate: "2025-06-26",
  originCity: "Vitória",
  originAirport: "VIX",
  countries: ["Portugal", "França", "Itália"],
  preferredCities: ["Lisboa", "Paris", "Roma"],
  travelers: {
    adults: 2,
    children: 0,
  },
  pace: "balanced",
  interests: ["história", "arte", "gastronomia", "fotografia", "arquitetura"],
  budgetLevel: "moderate",
  transportationPreferences: ["trem", "metrô"],
  dietaryPreferences: [],
  mandatoryPlaces: ["Torre Eiffel", "Coliseu", "Torre de Belém"],
};

export const DEMO_GENERATED_ITINERARY: GeneratedItinerary = {
  title: "Roteiro Lisboa → Paris → Roma - 12 dias",
  summary:
    "Viagem de 12 dias passando por Lisboa, Paris e Roma com ritmo equilibrado e orçamento moderado. Uma jornada pela história, arte e gastronomia da Europa.",
  totalDays: 12,
  estimatedTotalCostPerPerson: {
    min: 5800,
    max: 9200,
    currency: "BRL",
  },
  cities: [
    {
      city: "Lisboa",
      country: "Portugal",
      arrivalDate: "2025-06-15",
      departureDate: "2025-06-19",
      numberOfNights: 4,
      description:
        "Capital portuguesa com história milenar, miradouros deslumbrantes, pastéis de nata e o charme dos elétricos.",
      estimatedDailyCostPerPerson: { min: 400, max: 600, currency: "BRL" },
    },
    {
      city: "Paris",
      country: "França",
      arrivalDate: "2025-06-19",
      departureDate: "2025-06-23",
      numberOfNights: 4,
      description:
        "Cidade Luz com a Torre Eiffel, Louvre, Notre-Dame, gastronomia refinada e a atmosfera romântica dos boulevards.",
      estimatedDailyCostPerPerson: { min: 500, max: 700, currency: "BRL" },
    },
    {
      city: "Roma",
      country: "Itália",
      arrivalDate: "2025-06-23",
      departureDate: "2025-06-26",
      numberOfNights: 3,
      description:
        "Cidade Eterna com o Coliseu, Vaticano, Fontana di Trevi e milênios de história a cada esquina.",
      estimatedDailyCostPerPerson: { min: 450, max: 680, currency: "BRL" },
    },
  ],
  days: [
    // Day 1 - Arrival in Lisboa
    {
      dayNumber: 1,
      date: "2025-06-15",
      city: "Lisboa",
      country: "Portugal",
      title: "Chegada em Lisboa",
      summary:
        "Dia de chegada em Lisboa com acomodação e primeiro passeio pelo bairro de Alfama ao entardecer.",
      activities: [
        {
          id: "demo-d1-01",
          name: "Café da manhã",
          category: "refeição",
          description: "Café da manhã no avião ou no aeroporto de Lisboa.",
          suggestedStartTime: "08:00",
          suggestedEndTime: "09:00",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d1-02",
          name: "Chegada e acomodação",
          category: "logística",
          description:
            "Chegada ao Aeroporto Humberto Delgado, transfer de metrô ou táxi até o hotel na região da Baixa/Chiado. Check-in e descanso.",
          address: "Aeroporto de Lisboa, 1700-008 Lisboa",
          latitude: 38.7742,
          longitude: -9.1342,
          suggestedStartTime: "11:00",
          suggestedEndTime: "14:00",
          estimatedDurationMinutes: 180,
          estimatedCostPerPerson: { min: 30, max: 80, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d1-03",
          name: "Almoço no Mercado da Ribeira (Time Out Market)",
          category: "refeição",
          description:
            "Primeiro contato com a gastronomia portuguesa no mercado que reúne os melhores chefs de Lisboa sob um teto.",
          address: "Av. 24 de Julho 49, 1200-479 Lisboa",
          latitude: 38.7069,
          longitude: -9.1457,
          suggestedStartTime: "14:00",
          suggestedEndTime: "15:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 70, max: 120, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d1-04",
          name: "Passeio pelo Bairro de Alfama",
          category: "bairro",
          description:
            "Caminhada pelas ruelas medievais do bairro mais antigo de Lisboa, com seus miradouros, casas de fado e azulejos coloridos.",
          address: "Alfama, Lisboa",
          latitude: 38.7114,
          longitude: -9.1304,
          suggestedStartTime: "16:00",
          suggestedEndTime: "18:30",
          estimatedDurationMinutes: 150,
          estimatedCostPerPerson: { min: 0, max: 20, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d1-05",
          name: "Jantar com fado em Alfama",
          category: "refeição",
          description:
            "Jantar em casa de fado tradicional ouvindo a música portuguesa patrimônio imaterial da UNESCO.",
          address: "R. dos Remédios 176, 1100-443 Lisboa",
          latitude: 38.7126,
          longitude: -9.1270,
          suggestedStartTime: "20:00",
          suggestedEndTime: "22:30",
          estimatedDurationMinutes: 150,
          estimatedCostPerPerson: { min: 120, max: 200, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 220, max: 420, currency: "BRL" },
    },
    // Day 2 - Lisboa: Belém
    {
      dayNumber: 2,
      date: "2025-06-16",
      city: "Lisboa",
      country: "Portugal",
      title: "Lisboa: Belém e os Descobrimentos",
      summary:
        "Dia dedicado à zona de Belém com o Mosteiro dos Jerónimos, Torre de Belém e os famosos pastéis de nata.",
      activities: [
        {
          id: "demo-d2-01",
          name: "Café da manhã no hotel",
          category: "refeição",
          description: "Café da manhã buffet no hotel com especialidades portuguesas.",
          suggestedStartTime: "08:00",
          suggestedEndTime: "09:00",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d2-02",
          name: "Mosteiro dos Jerónimos",
          category: "monumento",
          description:
            "Visita à obra-prima do estilo manuelino, patrimônio mundial da UNESCO. Destaque para o claustro e a igreja com o túmulo de Vasco da Gama.",
          address: "Praça do Império, 1400-206 Lisboa",
          latitude: 38.6979,
          longitude: -9.2068,
          suggestedStartTime: "09:30",
          suggestedEndTime: "11:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 50, max: 70, currency: "BRL" },
          openingHours: ["10:00-17:30"],
          website: "http://www.mosteirojeronimos.gov.pt",
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d2-03",
          name: "Pastéis de Belém",
          category: "gastronomia",
          description:
            "Pausa para saborear os originais pastéis de nata na pastelaria mais famosa de Portugal, em funcionamento desde 1837.",
          address: "R. de Belém 84-92, 1300-085 Lisboa",
          latitude: 38.6975,
          longitude: -9.2030,
          suggestedStartTime: "11:45",
          suggestedEndTime: "12:30",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 15, max: 30, currency: "BRL" },
          openingHours: ["08:00-23:00"],
          website: "http://pasteisdebelem.pt",
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d2-04",
          name: "Almoço em Belém",
          category: "refeição",
          description:
            "Almoço em restaurante com vista para o Tejo, com bacalhau ou peixe grelhado fresco.",
          address: "R. de Belém, 1300-085 Lisboa",
          latitude: 38.6968,
          longitude: -9.2045,
          suggestedStartTime: "12:45",
          suggestedEndTime: "14:00",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 70, max: 120, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d2-05",
          name: "Torre de Belém",
          category: "monumento",
          description:
            "Visita à torre manuelina à beira do Tejo, símbolo dos Descobrimentos portugueses e patrimônio UNESCO.",
          address: "Av. Brasília, 1400-038 Lisboa",
          latitude: 38.6916,
          longitude: -9.2159,
          suggestedStartTime: "14:30",
          suggestedEndTime: "15:30",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 40, max: 60, currency: "BRL" },
          openingHours: ["10:00-17:30"],
          website: "http://www.torrebelem.gov.pt",
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d2-06",
          name: "Padrão dos Descobrimentos",
          category: "monumento",
          description:
            "Monumento em forma de caravela homenageando os navegadores portugueses. Vista panorâmica do terraço.",
          address: "Av. Brasília, 1400-038 Lisboa",
          latitude: 38.6936,
          longitude: -9.2091,
          suggestedStartTime: "16:00",
          suggestedEndTime: "17:00",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 30, max: 50, currency: "BRL" },
          openingHours: ["10:00-19:00"],
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d2-07",
          name: "Jantar na Baixa",
          category: "refeição",
          description:
            "Jantar em tasca tradicional na Baixa Pombalina com pratos de cozinha portuguesa e vinho do Alentejo.",
          address: "Rua Augusta, 1100-053 Lisboa",
          latitude: 38.7100,
          longitude: -9.1373,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 80, max: 140, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 285, max: 470, currency: "BRL" },
    },
    // Day 3 - Lisboa: Sintra day trip
    {
      dayNumber: 3,
      date: "2025-06-17",
      city: "Lisboa",
      country: "Portugal",
      title: "Bate-volta a Sintra",
      summary:
        "Dia inteiro em Sintra visitando o colorido Palácio da Pena e o Castelo dos Mouros com vistas deslumbrantes.",
      activities: [
        {
          id: "demo-d3-01",
          name: "Café da manhã no hotel",
          category: "refeição",
          description: "Café da manhã rápido antes de pegar o trem para Sintra.",
          suggestedStartTime: "07:30",
          suggestedEndTime: "08:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d3-02",
          name: "Trem Lisboa → Sintra",
          category: "transporte",
          description:
            "Trem da estação Rossio até Sintra (40 minutos). Comprar bilhete ida e volta na máquina.",
          address: "Estação do Rossio, 1100-205 Lisboa",
          latitude: 38.7147,
          longitude: -9.1411,
          suggestedStartTime: "08:30",
          suggestedEndTime: "09:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 12, max: 18, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d3-03",
          name: "Palácio da Pena",
          category: "palácio",
          description:
            "Visita ao palácio romântico mais emblemático de Portugal, com fachadas coloridas, terraços e jardins exuberantes no topo da serra.",
          address: "Estrada da Pena, 2710-609 Sintra",
          latitude: 38.7876,
          longitude: -9.3907,
          suggestedStartTime: "09:45",
          suggestedEndTime: "12:00",
          estimatedDurationMinutes: 135,
          estimatedCostPerPerson: { min: 70, max: 90, currency: "BRL" },
          openingHours: ["09:30-18:30"],
          website: "https://www.parquesdesintra.pt",
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d3-04",
          name: "Almoço em Sintra",
          category: "refeição",
          description:
            "Almoço no centro histórico de Sintra com queijadas e travesseiros, doces típicos da vila.",
          address: "Volta do Duche 12, 2710-631 Sintra",
          latitude: 38.7990,
          longitude: -9.3880,
          suggestedStartTime: "12:30",
          suggestedEndTime: "13:45",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 60, max: 100, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d3-05",
          name: "Castelo dos Mouros",
          category: "monumento",
          description:
            "Fortaleza medieval do século VIII com muralhas serpentinas e vistas panorâmicas de Sintra e do Atlântico.",
          address: "2710-405 Sintra",
          latitude: 38.7926,
          longitude: -9.3893,
          suggestedStartTime: "14:15",
          suggestedEndTime: "15:45",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 40, max: 55, currency: "BRL" },
          openingHours: ["09:30-18:00"],
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d3-06",
          name: "Centro Histórico de Sintra",
          category: "bairro",
          description:
            "Passeio pelo centro com o Palácio Nacional e suas chaminés cônicas, lojas de artesanato e cafés.",
          address: "Centro Histórico, 2710 Sintra",
          latitude: 38.7976,
          longitude: -9.3907,
          suggestedStartTime: "16:15",
          suggestedEndTime: "17:30",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 0, max: 30, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d3-07",
          name: "Retorno a Lisboa e jantar",
          category: "refeição",
          description:
            "Retorno de trem e jantar leve no Chiado com vinho verde e petiscos portugueses.",
          address: "Chiado, Lisboa",
          latitude: 38.7107,
          longitude: -9.1418,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 80, max: 130, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 262, max: 423, currency: "BRL" },
    },
    // Day 4 - Lisboa: Baixa, Chiado, Castelo
    {
      dayNumber: 4,
      date: "2025-06-18",
      city: "Lisboa",
      country: "Portugal",
      title: "Lisboa: Baixa, Chiado e Castelo",
      summary:
        "Explorando o coração de Lisboa com o Castelo de São Jorge, a Praça do Comércio e o elegante bairro do Chiado.",
      activities: [
        {
          id: "demo-d4-01",
          name: "Café da manhã no hotel",
          category: "refeição",
          description: "Café da manhã tranquilo no hotel antes do último dia em Lisboa.",
          suggestedStartTime: "08:00",
          suggestedEndTime: "09:00",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-02",
          name: "Castelo de São Jorge",
          category: "monumento",
          description:
            "Visita ao castelo mouro com vistas panorâmicas de 360° sobre Lisboa, o Tejo e a Ponte 25 de Abril.",
          address: "R. de Santa Cruz do Castelo, 1100-129 Lisboa",
          latitude: 38.7139,
          longitude: -9.1334,
          suggestedStartTime: "09:30",
          suggestedEndTime: "11:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 50, max: 70, currency: "BRL" },
          openingHours: ["09:00-21:00"],
          website: "http://castelodesaojorge.pt",
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-03",
          name: "Elétrico 28",
          category: "transporte",
          description:
            "Passeio no icônico bonde amarelo pelas colinas históricas de Lisboa, passando por Graça, Alfama e Estrela.",
          address: "Vários pontos, Lisboa",
          latitude: 38.7139,
          longitude: -9.1399,
          suggestedStartTime: "11:30",
          suggestedEndTime: "12:30",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 15, max: 25, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-04",
          name: "Almoço na Praça do Comércio",
          category: "refeição",
          description:
            "Almoço com vista para o Tejo num dos restaurantes com terraço na majestosa praça ribeirinha.",
          address: "Praça do Comércio, 1100-148 Lisboa",
          latitude: 38.7075,
          longitude: -9.1364,
          suggestedStartTime: "13:00",
          suggestedEndTime: "14:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 80, max: 140, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-05",
          name: "Bairro do Chiado e Livraria Bertrand",
          category: "bairro",
          description:
            "Passeio pelo elegante Chiado com a livraria mais antiga do mundo (1732), lojas de design e cafés históricos como A Brasileira.",
          address: "R. Garrett, 1200-203 Lisboa",
          latitude: 38.7107,
          longitude: -9.1418,
          suggestedStartTime: "15:00",
          suggestedEndTime: "16:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 0, max: 60, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-06",
          name: "Elevador de Santa Justa",
          category: "monumento",
          description:
            "Subida no elevador neogótico de ferro para vista panorâmica da Baixa e do Castelo de São Jorge.",
          address: "R. do Ouro, 1150-060 Lisboa",
          latitude: 38.7121,
          longitude: -9.1393,
          suggestedStartTime: "17:00",
          suggestedEndTime: "17:30",
          estimatedDurationMinutes: 30,
          estimatedCostPerPerson: { min: 15, max: 25, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d4-07",
          name: "Jantar de despedida de Lisboa",
          category: "refeição",
          description:
            "Jantar especial no Bairro Alto com marisco e vinhos portugueses, celebrando os dias em Lisboa.",
          address: "Bairro Alto, Lisboa",
          latitude: 38.7132,
          longitude: -9.1449,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 120, max: 200, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 280, max: 520, currency: "BRL" },
    },
    // Day 5 - Travel to Paris
    {
      dayNumber: 5,
      date: "2025-06-19",
      city: "Paris",
      country: "França",
      title: "Viagem Lisboa → Paris",
      summary:
        "Voo matinal para Paris, chegada ao hotel e primeiro passeio pelo Quartier Latin ao entardecer.",
      activities: [
        {
          id: "demo-d5-01",
          name: "Café da manhã rápido e check-out",
          category: "refeição",
          description: "Café da manhã no hotel, check-out e deslocamento ao aeroporto de Lisboa.",
          suggestedStartTime: "06:30",
          suggestedEndTime: "07:30",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d5-02",
          name: "Voo Lisboa → Paris (CDG)",
          category: "transporte",
          description:
            "Voo de aproximadamente 2h30 de Lisboa para Paris Charles de Gaulle. Chegada prevista por volta do meio-dia.",
          address: "Aeroporto de Lisboa, 1700-008 Lisboa",
          latitude: 38.7742,
          longitude: -9.1342,
          suggestedStartTime: "09:00",
          suggestedEndTime: "13:00",
          estimatedDurationMinutes: 240,
          estimatedCostPerPerson: { min: 200, max: 450, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d5-03",
          name: "Transfer e check-in em Paris",
          category: "logística",
          description:
            "RER B do aeroporto CDG até o centro. Check-in no hotel na região do Quartier Latin/Saint-Germain.",
          address: "Quartier Latin, 75005 Paris",
          latitude: 48.8498,
          longitude: 2.3447,
          suggestedStartTime: "13:30",
          suggestedEndTime: "15:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 30, max: 60, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d5-04",
          name: "Almoço tardio no Quartier Latin",
          category: "refeição",
          description:
            "Almoço num bistrô do bairro universitário com croque-monsieur ou salada niçoise e vinho da casa.",
          address: "Rue de la Huchette, 75005 Paris",
          latitude: 48.8523,
          longitude: 2.3464,
          suggestedStartTime: "15:15",
          suggestedEndTime: "16:30",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 70, max: 120, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d5-05",
          name: "Passeio pela Île de la Cité e Notre-Dame",
          category: "monumento",
          description:
            "Caminhada pela ilha histórica de Paris com vista exterior da Catedral de Notre-Dame, reaberta após restauração.",
          address: "6 Parvis Notre-Dame, 75004 Paris",
          latitude: 48.8530,
          longitude: 2.3499,
          suggestedStartTime: "17:00",
          suggestedEndTime: "18:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d5-06",
          name: "Jantar em Saint-Germain-des-Prés",
          category: "refeição",
          description:
            "Jantar em brasserie clássica parisiense com pato confitado ou steak-frites e crème brûlée.",
          address: "Boulevard Saint-Germain, 75006 Paris",
          latitude: 48.8539,
          longitude: 2.3338,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 100, max: 170, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 400, max: 800, currency: "BRL" },
    },
    // Day 6 - Paris: Eiffel & Champs-Élysées
    {
      dayNumber: 6,
      date: "2025-06-20",
      city: "Paris",
      country: "França",
      title: "Paris: Torre Eiffel e Champs-Élysées",
      summary:
        "Dia icônico com subida à Torre Eiffel, passeio pelos Champs-Élysées e cruzeiro noturno pelo Sena.",
      activities: [
        {
          id: "demo-d6-01",
          name: "Café da manhã em padaria francesa",
          category: "refeição",
          description:
            "Croissant, pain au chocolat e café crème numa boulangerie parisiense típica.",
          address: "Rue de Buci, 75006 Paris",
          latitude: 48.8536,
          longitude: 2.3368,
          suggestedStartTime: "08:00",
          suggestedEndTime: "08:45",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 30, max: 50, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d6-02",
          name: "Torre Eiffel",
          category: "monumento",
          description:
            "Subida ao 2º andar da Torre Eiffel (ou topo) para vista panorâmica de 360° sobre toda Paris. Reservar ingresso com antecedência.",
          address: "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
          latitude: 48.8584,
          longitude: 2.2945,
          suggestedStartTime: "09:30",
          suggestedEndTime: "11:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 80, max: 140, currency: "BRL" },
          openingHours: ["09:30-23:45"],
          website: "https://www.toureiffel.paris",
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d6-03",
          name: "Jardins do Trocadéro",
          category: "parque",
          description:
            "Vista clássica da Torre Eiffel desde a esplanada do Trocadéro, com fontes e jardins simétricos.",
          address: "Place du Trocadéro, 75016 Paris",
          latitude: 48.8616,
          longitude: 2.2886,
          suggestedStartTime: "11:45",
          suggestedEndTime: "12:15",
          estimatedDurationMinutes: 30,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d6-04",
          name: "Almoço no Champ de Mars",
          category: "refeição",
          description:
            "Almoço em café com vista para a Torre Eiffel ou piquenique nos jardins do Champ de Mars.",
          address: "Champ de Mars, 75007 Paris",
          latitude: 48.8556,
          longitude: 2.2986,
          suggestedStartTime: "12:30",
          suggestedEndTime: "14:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 70, max: 130, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d6-05",
          name: "Champs-Élysées e Arco do Triunfo",
          category: "avenida",
          description:
            "Passeio pela avenida mais famosa do mundo até o Arco do Triunfo. Subida ao terraço para vista das 12 avenidas radiantes.",
          address: "Place Charles de Gaulle, 75008 Paris",
          latitude: 48.8738,
          longitude: 2.2950,
          suggestedStartTime: "14:30",
          suggestedEndTime: "16:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 60, max: 90, currency: "BRL" },
          openingHours: ["10:00-23:00"],
          website: "http://www.paris-arc-de-triomphe.fr",
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d6-06",
          name: "Jardim de Luxemburgo",
          category: "parque",
          description:
            "Descanso no mais elegante jardim parisiense, com fontes, estátuas e cadeiras verdes ao sol.",
          address: "75006 Paris",
          latitude: 48.8462,
          longitude: 2.3372,
          suggestedStartTime: "17:00",
          suggestedEndTime: "18:00",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d6-07",
          name: "Cruzeiro noturno pelo Rio Sena",
          category: "passeio",
          description:
            "Passeio de barco de 1 hora vendo Notre-Dame, Louvre, Museu d'Orsay e Torre Eiffel iluminados ao anoitecer.",
          address: "Port de la Bourdonnais, 75007 Paris",
          latitude: 48.8600,
          longitude: 2.2900,
          suggestedStartTime: "20:30",
          suggestedEndTime: "21:45",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 70, max: 110, currency: "BRL" },
          openingHours: ["10:00-22:30"],
          website: "https://www.bateaux-mouches.fr",
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 310, max: 520, currency: "BRL" },
    },
    // Day 7 - Paris: Louvre & Montmartre
    {
      dayNumber: 7,
      date: "2025-06-21",
      city: "Paris",
      country: "França",
      title: "Paris: Louvre e Montmartre",
      summary:
        "Manhã no Museu do Louvre com Mona Lisa e Vênus de Milo, tarde artística em Montmartre com Sacré-Cœur.",
      activities: [
        {
          id: "demo-d7-01",
          name: "Café da manhã",
          category: "refeição",
          description: "Café da manhã no hotel ou em café próximo ao Louvre.",
          suggestedStartTime: "07:30",
          suggestedEndTime: "08:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 30, max: 50, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d7-02",
          name: "Museu do Louvre",
          category: "museu",
          description:
            "Visita ao maior museu do mundo. Destaques: Mona Lisa, Vênus de Milo, Vitória de Samotrácia e as galerias de pintura francesa.",
          address: "Rue de Rivoli, 75001 Paris",
          latitude: 48.8606,
          longitude: 2.3376,
          suggestedStartTime: "09:00",
          suggestedEndTime: "13:00",
          estimatedDurationMinutes: 240,
          estimatedCostPerPerson: { min: 80, max: 110, currency: "BRL" },
          openingHours: ["09:00-18:00"],
          website: "https://www.louvre.fr",
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d7-03",
          name: "Almoço no Jardin des Tuileries",
          category: "refeição",
          description:
            "Almoço em café no jardim das Tulherias, entre o Louvre e a Place de la Concorde.",
          address: "Jardin des Tuileries, 75001 Paris",
          latitude: 48.8634,
          longitude: 2.3275,
          suggestedStartTime: "13:15",
          suggestedEndTime: "14:30",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 80, max: 140, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d7-04",
          name: "Montmartre e Sacré-Cœur",
          category: "bairro",
          description:
            "Subida pela colina de Montmartre, praça dos artistas (Place du Tertre), e visita à basílica branca com vista panorâmica de Paris.",
          address: "35 Rue du Chevalier de la Barre, 75018 Paris",
          latitude: 48.8867,
          longitude: 2.3431,
          suggestedStartTime: "15:30",
          suggestedEndTime: "18:00",
          estimatedDurationMinutes: 150,
          estimatedCostPerPerson: { min: 0, max: 30, currency: "BRL" },
          openingHours: ["06:00-22:30"],
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d7-05",
          name: "Jantar em Montmartre",
          category: "refeição",
          description:
            "Jantar em restaurante aconchegante de Montmartre com fondue ou tartiflette e vinho tinto francês.",
          address: "Rue Lepic, 75018 Paris",
          latitude: 48.8845,
          longitude: 2.3348,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 100, max: 170, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 290, max: 500, currency: "BRL" },
    },
    // Day 8 - Paris: Versailles
    {
      dayNumber: 8,
      date: "2025-06-22",
      city: "Paris",
      country: "França",
      title: "Bate-volta a Versalhes",
      summary:
        "Dia inteiro no Palácio de Versalhes com Salão dos Espelhos, jardins geométricos e Grand Trianon.",
      activities: [
        {
          id: "demo-d8-01",
          name: "Café da manhã no hotel",
          category: "refeição",
          description: "Café da manhã antes da viagem a Versalhes.",
          suggestedStartTime: "07:30",
          suggestedEndTime: "08:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 30, max: 50, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d8-02",
          name: "RER C para Versalhes",
          category: "transporte",
          description:
            "Trem RER C até Versailles Rive Gauche (35-40 minutos do centro de Paris).",
          suggestedStartTime: "08:30",
          suggestedEndTime: "09:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 20, max: 30, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d8-03",
          name: "Palácio de Versalhes",
          category: "palácio",
          description:
            "Visita aos apartamentos reais, Salão dos Espelhos, capela e galeria de batalhas. Audioguia incluído.",
          address: "Place d'Armes, 78000 Versailles",
          latitude: 48.8049,
          longitude: 2.1204,
          suggestedStartTime: "09:30",
          suggestedEndTime: "12:30",
          estimatedDurationMinutes: 180,
          estimatedCostPerPerson: { min: 100, max: 140, currency: "BRL" },
          openingHours: ["09:00-18:30"],
          website: "http://www.chateauversailles.fr",
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d8-04",
          name: "Almoço nos Jardins de Versalhes",
          category: "refeição",
          description:
            "Almoço no La Petite Venise ou piquenique nos jardins do palácio.",
          address: "Jardins de Versailles, 78000 Versailles",
          latitude: 48.8040,
          longitude: 2.1130,
          suggestedStartTime: "12:45",
          suggestedEndTime: "14:00",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 70, max: 130, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d8-05",
          name: "Jardins e Grand Trianon",
          category: "jardins",
          description:
            "Passeio pelos jardins geométricos de Le Nôtre, fontes, bosques e visita ao Grand Trianon de Maria Antonieta.",
          address: "Domaine de Trianon, 78000 Versailles",
          latitude: 48.8133,
          longitude: 2.1070,
          suggestedStartTime: "14:15",
          suggestedEndTime: "17:00",
          estimatedDurationMinutes: 165,
          estimatedCostPerPerson: { min: 50, max: 70, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d8-06",
          name: "Jantar em Paris",
          category: "refeição",
          description:
            "Jantar de despedida de Paris em brasserie clássica com plateau de fruits de mer ou coq au vin.",
          address: "Rue de Seine, 75006 Paris",
          latitude: 48.8554,
          longitude: 2.3362,
          suggestedStartTime: "19:30",
          suggestedEndTime: "21:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 120, max: 200, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 390, max: 620, currency: "BRL" },
    },
    // Day 9 - Travel to Roma
    {
      dayNumber: 9,
      date: "2025-06-23",
      city: "Roma",
      country: "Itália",
      title: "Viagem Paris → Roma",
      summary:
        "Voo matinal para Roma, chegada à Cidade Eterna e primeiro passeio pela Fontana di Trevi e Panteão.",
      activities: [
        {
          id: "demo-d9-01",
          name: "Café da manhã e check-out",
          category: "refeição",
          description: "Café rápido, check-out e deslocamento ao aeroporto CDG ou Orly.",
          suggestedStartTime: "06:30",
          suggestedEndTime: "07:30",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d9-02",
          name: "Voo Paris → Roma (FCO)",
          category: "transporte",
          description:
            "Voo de aproximadamente 2 horas de Paris para Roma Fiumicino. Chegada prevista ao meio-dia.",
          address: "Aéroport Charles de Gaulle, 95700 Roissy-en-France",
          latitude: 49.0097,
          longitude: 2.5479,
          suggestedStartTime: "09:00",
          suggestedEndTime: "12:30",
          estimatedDurationMinutes: 210,
          estimatedCostPerPerson: { min: 180, max: 400, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
        {
          id: "demo-d9-03",
          name: "Transfer e check-in em Roma",
          category: "logística",
          description:
            "Leonardo Express até Roma Termini e check-in no hotel na região do Centro Storico.",
          address: "Via del Corso, 00186 Roma",
          latitude: 41.9027,
          longitude: 12.4803,
          suggestedStartTime: "13:00",
          suggestedEndTime: "14:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 50, max: 80, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d9-04",
          name: "Almoço romano",
          category: "refeição",
          description:
            "Primeiro almoço italiano com cacio e pepe, supplì e um copo de vinho branco local.",
          address: "Via delle Muratte, 00187 Roma",
          latitude: 41.9003,
          longitude: 12.4825,
          suggestedStartTime: "14:45",
          suggestedEndTime: "16:00",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 60, max: 110, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d9-05",
          name: "Fontana di Trevi",
          category: "monumento",
          description:
            "Visita à fonte barroca mais famosa do mundo. Jogue uma moeda com a mão direita sobre o ombro esquerdo para garantir o retorno.",
          address: "Piazza di Trevi, 00187 Roma",
          latitude: 41.9009,
          longitude: 12.4833,
          suggestedStartTime: "16:30",
          suggestedEndTime: "17:00",
          estimatedDurationMinutes: 30,
          estimatedCostPerPerson: { min: 0, max: 5, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d9-06",
          name: "Panteão",
          category: "monumento",
          description:
            "Templo romano perfeitamente preservado há 2000 anos, com a impressionante cúpula de concreto e seu óculo aberto ao céu.",
          address: "Piazza della Rotonda, 00186 Roma",
          latitude: 41.8986,
          longitude: 12.4769,
          suggestedStartTime: "17:15",
          suggestedEndTime: "18:00",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 25, max: 40, currency: "BRL" },
          openingHours: ["09:00-19:00"],
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d9-07",
          name: "Jantar em Trastevere",
          category: "refeição",
          description:
            "Jantar no bairro mais charmoso de Roma com pasta alla carbonara autêntica e tiramisù.",
          address: "Piazza di Santa Maria in Trastevere, 00153 Roma",
          latitude: 41.8895,
          longitude: 12.4699,
          suggestedStartTime: "20:00",
          suggestedEndTime: "21:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 80, max: 150, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 395, max: 785, currency: "BRL" },
    },
    // Day 10 - Roma: Coliseu e Roma Antiga
    {
      dayNumber: 10,
      date: "2025-06-24",
      city: "Roma",
      country: "Itália",
      title: "Roma Antiga: Coliseu e Fórum",
      summary:
        "Dia dedicado à Roma Antiga com Coliseu, Fórum Romano, Palatino e Piazza Navona ao entardecer.",
      activities: [
        {
          id: "demo-d10-01",
          name: "Café da manhã italiano",
          category: "refeição",
          description:
            "Cornetto e cappuccino num bar italiano tradicional, de pé no balcão como os romanos.",
          address: "Via del Corso, 00186 Roma",
          latitude: 41.9000,
          longitude: 12.4800,
          suggestedStartTime: "07:30",
          suggestedEndTime: "08:00",
          estimatedDurationMinutes: 30,
          estimatedCostPerPerson: { min: 15, max: 25, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d10-02",
          name: "Coliseu",
          category: "monumento",
          description:
            "Visita ao maior anfiteatro romano, com acesso à arena e pisos superiores. Audioguia recomendado para entender a história dos gladiadores.",
          address: "Piazza del Colosseo, 1, 00184 Roma",
          latitude: 41.8902,
          longitude: 12.4922,
          suggestedStartTime: "08:30",
          suggestedEndTime: "10:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 80, max: 120, currency: "BRL" },
          openingHours: ["09:00-19:00"],
          website: "https://www.colosseumrome.it",
          bookingRecommended: true,
          source: "demonstração",
          notes: ["Ingresso combinado com Fórum Romano e Palatino válido por 2 dias."],
        },
        {
          id: "demo-d10-03",
          name: "Fórum Romano e Palatino",
          category: "sítio arqueológico",
          description:
            "Centro político da Roma Antiga com templos, arcos triunfais e as ruínas dos palácios imperiais no monte Palatino.",
          address: "Via della Salara Vecchia, 5/6, 00186 Roma",
          latitude: 41.8925,
          longitude: 12.4853,
          suggestedStartTime: "10:45",
          suggestedEndTime: "13:00",
          estimatedDurationMinutes: 135,
          estimatedCostPerPerson: { min: 0, max: 0, currency: "BRL" },
          openingHours: ["09:00-19:00"],
          bookingRecommended: true,
          source: "demonstração",
          notes: ["Incluído no ingresso do Coliseu."],
        },
        {
          id: "demo-d10-04",
          name: "Almoço perto do Coliseu",
          category: "refeição",
          description:
            "Almoço em trattoria nos arredores, com amatriciana, saltimbocca alla romana e vinho dos Castelli.",
          address: "Via dei Fori Imperiali, 00184 Roma",
          latitude: 41.8930,
          longitude: 12.4880,
          suggestedStartTime: "13:15",
          suggestedEndTime: "14:30",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 70, max: 130, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d10-05",
          name: "Piazza Navona",
          category: "praça",
          description:
            "Passeio pela praça barroca com as três fontes de Bernini, artistas de rua e café gelato artesanal.",
          address: "Piazza Navona, 00186 Roma",
          latitude: 41.8992,
          longitude: 12.4731,
          suggestedStartTime: "15:30",
          suggestedEndTime: "16:30",
          estimatedDurationMinutes: 60,
          estimatedCostPerPerson: { min: 10, max: 30, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d10-06",
          name: "Campo de' Fiori e passeggiata",
          category: "praça",
          description:
            "Passeio vespertino pela praça do mercado e ruas do centro histórico, parando para um aperitivo.",
          address: "Campo de' Fiori, 00186 Roma",
          latitude: 41.8956,
          longitude: 12.4722,
          suggestedStartTime: "17:00",
          suggestedEndTime: "18:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 30, max: 60, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d10-07",
          name: "Jantar romano",
          category: "refeição",
          description:
            "Jantar em restaurante com mesas ao ar livre no centro histórico, com tonnarelli cacio e pepe e abbacchio.",
          address: "Via dei Giubbonari, 00186 Roma",
          latitude: 41.8950,
          longitude: 12.4730,
          suggestedStartTime: "20:00",
          suggestedEndTime: "21:30",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 90, max: 160, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 295, max: 525, currency: "BRL" },
    },
    // Day 11 - Roma: Vaticano
    {
      dayNumber: 11,
      date: "2025-06-25",
      city: "Roma",
      country: "Itália",
      title: "Vaticano e Trastevere",
      summary:
        "Manhã nos Museus do Vaticano e Capela Sistina, Basílica de São Pedro e noite charmosa em Trastevere.",
      activities: [
        {
          id: "demo-d11-01",
          name: "Café da manhã",
          category: "refeição",
          description: "Café da manhã leve antes de ir ao Vaticano (recomenda-se chegar cedo).",
          suggestedStartTime: "07:00",
          suggestedEndTime: "07:30",
          estimatedDurationMinutes: 30,
          estimatedCostPerPerson: { min: 15, max: 25, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d11-02",
          name: "Museus do Vaticano e Capela Sistina",
          category: "museu",
          description:
            "Visita às galerias papais culminando na Capela Sistina com o teto pintado por Michelangelo. Ingresso com horário marcado essencial.",
          address: "Viale Vaticano, 00165 Roma",
          latitude: 41.9065,
          longitude: 12.4536,
          suggestedStartTime: "08:00",
          suggestedEndTime: "12:00",
          estimatedDurationMinutes: 240,
          estimatedCostPerPerson: { min: 100, max: 150, currency: "BRL" },
          openingHours: ["09:00-18:00"],
          website: "https://www.museivaticani.va",
          bookingRecommended: true,
          source: "demonstração",
          notes: ["Reservar com 2-3 semanas de antecedência. Filas sem reserva podem passar de 2 horas."],
        },
        {
          id: "demo-d11-03",
          name: "Basílica de São Pedro",
          category: "igreja",
          description:
            "Visita à maior igreja católica do mundo com a Pietà de Michelangelo. Opção de subir à cúpula para vista panorâmica.",
          address: "Piazza San Pietro, 00120 Città del Vaticano",
          latitude: 41.9022,
          longitude: 12.4539,
          suggestedStartTime: "12:15",
          suggestedEndTime: "13:45",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 0, max: 50, currency: "BRL" },
          openingHours: ["07:00-19:00"],
          website: "http://www.vatican.va",
          bookingRecommended: false,
          source: "demonstração",
          notes: ["Entrada gratuita na basílica. Cúpula: pago (elevador + escada ou só escada)."],
        },
        {
          id: "demo-d11-04",
          name: "Almoço perto do Vaticano",
          category: "refeição",
          description:
            "Almoço em trattoria no bairro Prati com pizza romana al taglio e supplì.",
          address: "Via Cola di Rienzo, 00192 Roma",
          latitude: 41.9071,
          longitude: 12.4637,
          suggestedStartTime: "14:00",
          suggestedEndTime: "15:15",
          estimatedDurationMinutes: 75,
          estimatedCostPerPerson: { min: 50, max: 90, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d11-05",
          name: "Castel Sant'Angelo",
          category: "monumento",
          description:
            "Antigo mausoléu do imperador Adriano, fortaleza papal com passagem secreta ao Vaticano e terraço panorâmico.",
          address: "Lungotevere Castello, 50, 00193 Roma",
          latitude: 41.9031,
          longitude: 12.4663,
          suggestedStartTime: "15:30",
          suggestedEndTime: "17:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 60, max: 80, currency: "BRL" },
          openingHours: ["09:00-19:30"],
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d11-06",
          name: "Passeio por Trastevere",
          category: "bairro",
          description:
            "Caminhada ao entardecer pelas ruelas de Trastevere com igrejas medievais, grafites artísticos e gelaterias.",
          address: "Trastevere, Roma",
          latitude: 41.8895,
          longitude: 12.4699,
          suggestedStartTime: "17:30",
          suggestedEndTime: "19:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 10, max: 30, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d11-07",
          name: "Jantar de despedida em Trastevere",
          category: "refeição",
          description:
            "Último jantar da viagem em restaurante familiar com pasta fresca, porchetta e vinho Frascati. Brinde à Cidade Eterna.",
          address: "Via della Scala, 00153 Roma",
          latitude: 41.8901,
          longitude: 12.4675,
          suggestedStartTime: "20:00",
          suggestedEndTime: "22:00",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 100, max: 180, currency: "BRL" },
          bookingRecommended: true,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 335, max: 605, currency: "BRL" },
    },
    // Day 12 - Departure from Roma
    {
      dayNumber: 12,
      date: "2025-06-26",
      city: "Roma",
      country: "Itália",
      title: "Partida de Roma",
      summary:
        "Último passeio matinal pela Escadaria da Praça de Espanha e Via Condotti antes do voo de retorno.",
      activities: [
        {
          id: "demo-d12-01",
          name: "Café da manhã no hotel",
          category: "refeição",
          description: "Último café da manhã italiano com cornetto alla crema e cappuccino.",
          suggestedStartTime: "07:30",
          suggestedEndTime: "08:15",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 15, max: 25, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d12-02",
          name: "Escadaria da Praça de Espanha e Via Condotti",
          category: "monumento",
          description:
            "Passeio matinal pela escadaria do século XVIII, fonte Barcaccia e a elegante Via Condotti com lojas de grife.",
          address: "Piazza di Spagna, 00187 Roma",
          latitude: 41.9060,
          longitude: 12.4823,
          suggestedStartTime: "08:30",
          suggestedEndTime: "10:00",
          estimatedDurationMinutes: 90,
          estimatedCostPerPerson: { min: 0, max: 30, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d12-03",
          name: "Último gelato e compras",
          category: "gastronomia",
          description:
            "Gelato artesanal de despedida e últimas compras de lembranças (azeite, pasta seca, limoncello).",
          address: "Via della Croce, 00187 Roma",
          latitude: 41.9065,
          longitude: 12.4795,
          suggestedStartTime: "10:15",
          suggestedEndTime: "11:00",
          estimatedDurationMinutes: 45,
          estimatedCostPerPerson: { min: 20, max: 80, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
        {
          id: "demo-d12-04",
          name: "Check-out e ida ao aeroporto",
          category: "logística",
          description:
            "Check-out do hotel, Leonardo Express até o aeroporto Fiumicino para voo de retorno ao Brasil.",
          address: "Roma Termini, 00185 Roma",
          latitude: 41.9010,
          longitude: 12.5015,
          suggestedStartTime: "11:30",
          suggestedEndTime: "13:30",
          estimatedDurationMinutes: 120,
          estimatedCostPerPerson: { min: 50, max: 80, currency: "BRL" },
          bookingRecommended: false,
          source: "demonstração",
        },
      ],
      estimatedDailyCostPerPerson: { min: 85, max: 215, currency: "BRL" },
    },
  ],
  warnings: [
    "Viagens entre cidades por avião geram custos adicionais de transporte não incluídos na estimativa diária.",
    "Em junho, Lisboa e Roma podem ter temperaturas acima de 30°C — leve protetor solar e roupas leves.",
  ],
  recommendations: [
    "Reserve ingressos para Torre Eiffel, Louvre, Museus do Vaticano e Coliseu com 2-3 semanas de antecedência.",
    "Considere o Paris Museum Pass (2 ou 4 dias) para economizar em atrações e evitar filas.",
    "Para voos entre cidades (Lisboa→Paris, Paris→Roma), companhias low-cost como Vueling e EasyJet oferecem bons preços se reservados com antecedência.",
    "Leve um adaptador de tomada universal — Portugal/França usam tipo C/F, Itália usa tipo L.",
    "Considere um seguro viagem que cubra cancelamentos e emergências médicas na Europa.",
    "Mantenha cópias digitais de documentos importantes (passaporte, reservas, seguro) no celular e em nuvem.",
  ],
};
